validate parasymbolic matrix in python
CoronaHakab/CoronaHakabModel pull request #269
Opened 2020-04-17 15:43 UTC by rlfreiman

validate parasymbolic matrix in python via existing c++ code

2020-04-17 17:19 UTC, bentheiii approved these changes

2020-04-17 20:09 UTC, tal-nc approved these changes

2020-04-17 20:42 UTC, bgmoshe requested changes
Small fix

2020-04-17 20:42 UTC, bgmoshe commented on src/corona_hakab_model/update_matrix.py
> +                    assert self.matrix.get(row_index, column_index) == self.matrix.get(column_index, row_index)
Please instead of asserting return the value of the validation.
This can be usefull if we will want to take some measures =/= asserting on spot.
The code that uses validate_matrix can assert

2020-04-17 20:42 UTC, bgmoshe commented on src/corona_hakab_model/update_matrix.py
> +                    assert self.matrix.get(row_index, column_index) == self.matrix.get(column_index, row_index)
Also, when asserting please give the exact reason for which the matrix is not valid.

2020-04-18 17:50 UTC, bgmoshe approved these changes

2020-04-18 17:50 UTC, merged