Add age dependancy to corona disease pathway
CoronaHakab/CoronaHakabModel pull request #341
Opened 2020-04-26 13:43 UTC by bgmoshe

2020-04-26 13:45 UTC, bgmoshe commented
@RoyIsland  @tal-nc I did not finish all of this. The part you see is mainly some code cleaning to get rid of rvs

2020-04-26 14:17 UTC, RoyIsland commented on src/corona_hakab_model/consts.py
> +    latent_to_pre_symptomatic_days = dist(1, 5, 10)
you have to add a type hint in order for the config loading to work

2020-04-26 15:16 UTC, tal-nc commented
Overall looks good.
Just 2 points:
firstly, As Roy said, you must add type hints in order to allow loading from a file. Callable[[Optional[int]], int] should do.
secondly, why do we still need 'get_numpy_uniform_dist'? you can just implement it inside dist.

2020-04-26 15:21 UTC, bgmoshe commented
> Overall looks good.
> Just 2 points:
> firstly, As Roy said, you must add type hints in order to allow loading from a file. Callable[[Optional[int]], int] should do.
> secondly, why do we still need 'get_numpy_uniform_dist'? you can just implement it inside dist.

You are right, I forgot about this, I'll fix this now with a small fix I need to push

2020-04-28 11:47 UTC, bgmoshe commented
![main](https://user-images.githubusercontent.com/33910305/80483662-242c4180-895f-11ea-8628-64341c1a9666.png)
![pathway](https://user-images.githubusercontent.com/33910305/80483665-24c4d800-895f-11ea-9dab-5041b55588c9.png)

2020-04-28 14:56 UTC, bgmoshe commented
[rvs_numpy_binom_diff.zip](https://github.com/CoronaHakab/CoronaHakabModel/files/4546603/rvs_numpy_binom_diff.zip)

2020-04-28 14:57 UTC, meirhalachmi requested changes

2020-04-28 14:57 UTC, meirhalachmi commented on src/corona_hakab_model/consts.py
> +    latent_to_latent_asymp_begin_prob: BucketDict[int, Union[float, type(...)]] = BucketDict({8: 0.3})
FOR HEAVEN'S SAKE - pre-define this type somewhere above and use the new alias here.

2020-04-28 14:57 UTC, meirhalachmi commented on src/corona_hakab_model/Parameters/simulation_parameters_example.py
> +    "latent_to_latent_asymp_begin_prob": BucketDict({8: 0.3}),
The 8 does kinda confuse. Just fucking use 0 as the default key like a normal person please.

2020-04-28 15:17 UTC, meirhalachmi approved these changes

2020-04-28 15:17 UTC, merged