Fixed small build_win.py bug.
CoronaHakab/CoronaHakabModel pull request #357
Opened 2020-04-29 19:50 UTC by bgmoshe

Also, added set method for col coeffs

2020-05-01 16:34 UTC, meirhalachmi requested changes

2020-05-01 16:34 UTC, meirhalachmi commented on src/corona_hakab_model/parasymbolic_matrix/parasymbolic.cpp
> +void ParasymbolicMatrix::set_sub_row(size_t component, size_t row, dtype coeff){
You don't need to add them to the .hpp too?

2020-05-01 16:34 UTC, meirhalachmi commented on src/corona_hakab_model/update_matrix.py
> +        if agents_ids_to_rest is None:
to_reset* (typo)

2020-05-02 09:15 UTC, bgmoshe commented
@meirhalachmi  @RoyIsland  Some bug happened, try to rebase and now it seems like I have 18 changed files. When reveiwing please look directly at commits

2020-05-03 11:15 UTC, meirhalachmi approved these changes

2020-05-03 11:15 UTC, merged