Feature/getting out of isolation
CoronaHakab/CoronaHakabModel pull request #373
Opened 2020-05-08 13:53 UTC by bgmoshe

2020-05-09 10:24 UTC, meirhalachmi requested changes
Didn't finish reviewing it yet

2020-05-09 10:24 UTC, meirhalachmi commented on src/corona_hakab_model/consts.py
> +    isolation_factor: IsolationFactorsType = {
re-write the comment "# reduce agent's relations strength by a factor."

2020-05-09 10:24 UTC, meirhalachmi commented on src/corona_hakab_model/consts.py
> +            has_symptoms=True,
Not sure about that. Make sure with someone

2020-05-09 10:24 UTC, meirhalachmi commented on src/corona_hakab_model/manager.py
> +    def progress_isolations(self):
Don't you think that at least some of this logic should be in the HealthCareManager?

2020-05-10 12:23 UTC, closed without merging

2020-05-10 12:25 UTC, bgmoshe commented
@meirhalachmi  Oops ....